/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Address;
import Business.Person;

/**
 *
 * @author vivekdalal
 */
public class MainJFrame extends javax.swing.JFrame {

    private Person person;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        //Initialize the values of Product and display on the Panel
        person = new Person();

        populatePersonObj();

        displayPerson();
    }

    private void displayPerson() {
        firstNameTxtFLd.setText(person.getFirstName());
        firstNameTxtFLd.setEnabled(false);
        lastNameTxtFld.setText(person.getLastName());
        lastNameTxtFld.setEnabled(false);
        dobTxtFld.setText(person.getDob());
        dobTxtFld.setEnabled(false);
        ssnTxtFld.setText(person.getSsn());
        ssnTxtFld.setEnabled(false);

        //Setting work address
        addrLn1WrkTxtFLd.setText(person.getWorkAddress().getAddrLn1());
        addrLn1WrkTxtFLd.setEnabled(false);
        addrLn2WrkTxtFLd.setText(person.getWorkAddress().getAddrLn2());
        addrLn2WrkTxtFLd.setEnabled(false);
        cityWrkTxtFLd.setText(person.getWorkAddress().getCity());
        cityWrkTxtFLd.setEnabled(false);
        stateWrkTxtFLd.setText(person.getWorkAddress().getState());
        stateWrkTxtFLd.setEnabled(false);
        zipWrkTxtFLd.setText(person.getWorkAddress().getZipCd());
        zipWrkTxtFLd.setEnabled(false);

        //Setting home address
        addrLn1HmTxtFLd.setText(person.getHomeAddress().getAddrLn1());
        addrLn1HmTxtFLd.setEnabled(false);
        addrLn2HmTxtFLd.setText(person.getHomeAddress().getAddrLn2());
        addrLn2HmTxtFLd.setEnabled(false);
        cityHmTxtFLd.setText(person.getHomeAddress().getCity());
        cityHmTxtFLd.setEnabled(false);
        stateHmTxtFLd.setText(person.getHomeAddress().getState());
        stateHmTxtFLd.setEnabled(false);
        zipHmTxtFLd.setText(person.getHomeAddress().getZipCd());
        zipHmTxtFLd.setEnabled(false);

        //Setting the local address
        addrLn1LclTxtFLd.setText(person.getLocalAddress().getAddrLn1());
        addrLn1LclTxtFLd.setEnabled(false);
        addrLn2LclTxtFLd.setText(person.getLocalAddress().getAddrLn2());
        addrLn2LclTxtFLd.setEnabled(false);
        cityLclTxtFLd.setText(person.getLocalAddress().getCity());
        cityLclTxtFLd.setEnabled(false);
        stateLclTxtFLd.setText(person.getLocalAddress().getState());
        stateLclTxtFLd.setEnabled(false);
        zipLclTxtFLd.setText(person.getLocalAddress().getZipCd());
        zipLclTxtFLd.setEnabled(false);

    }

    private Person populatePersonObj() {

        //Setting Person name details
        person.setFirstName("John");
        person.setLastName("Doe");

        //Setting other personal details
        person.setSsn("123123123");
        person.setDob("01/01/1991");

        //Creating 3 address Objects for Work, Home and Local address respectively
        Address workAddress = new Address();
        Address homeAddress = new Address();
        Address localAddress = new Address();

        //Setting workAddress details
        workAddress.setAddrLn1("130 Hurtig Hall");
        workAddress.setAddrLn2("2C");
        workAddress.setCity("Boston");
        workAddress.setState("MA");
        workAddress.setZipCd("02118");

        //Setting localAddress details
        localAddress.setAddrLn1("22 Saint Cyprians PL");
        localAddress.setAddrLn2("3L");
        localAddress.setCity("Boston");
        localAddress.setState("MA");
        localAddress.setZipCd("02120");

        //Setting homeAddress details
        homeAddress.setAddrLn1("704 Bhoomi Apartment");
        homeAddress.setAddrLn2("Mahavir Nagar, Kandivali West");
        homeAddress.setCity("Mumbai");
        homeAddress.setState("MH");
        homeAddress.setZipCd("400067");

        //Setting the addresses into the Person object.
        person.setWorkAddress(workAddress);
        person.setHomeAddress(homeAddress);
        person.setLocalAddress(localAddress);
        return person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addrLn1WrkTxtFLd = new javax.swing.JTextField();
        ssnTxtFld = new javax.swing.JTextField();
        dobTxtFld = new javax.swing.JTextField();
        lastNameTxtFld = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        firstNameTxtFLd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        addrLn2WrkTxtFLd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cityWrkTxtFLd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        stateWrkTxtFLd = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        zipWrkTxtFLd = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        addrLn1HmTxtFLd = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        addrLn2HmTxtFLd = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cityHmTxtFLd = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        stateHmTxtFLd = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        zipHmTxtFLd = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        zipLclTxtFLd = new javax.swing.JTextField();
        stateLclTxtFLd = new javax.swing.JTextField();
        cityLclTxtFLd = new javax.swing.JTextField();
        addrLn2LclTxtFLd = new javax.swing.JTextField();
        addrLn1LclTxtFLd = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 20)); // NOI18N
        jLabel1.setText("Personal Information");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, 236, 40));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel2.setText("Local Address");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 260, 30));

        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 117, -1, -1));

        jLabel4.setText("DOB");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 79, -1, -1));

        jLabel5.setText("SSN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 117, -1, -1));

        addrLn1WrkTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrLn1WrkTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(addrLn1WrkTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 200, 30));
        jPanel1.add(ssnTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 112, 200, 30));

        dobTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTxtFldActionPerformed(evt);
            }
        });
        jPanel1.add(dobTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 74, 200, 30));

        lastNameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTxtFldActionPerformed(evt);
            }
        });
        jPanel1.add(lastNameTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 200, 30));

        jLabel6.setText("Addr Ln 1");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel7.setText("Work Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 260, 30));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel8.setText("Home Address");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 260, 30));

        jLabel9.setText("Last Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 117, -1, -1));

        jLabel10.setText("First Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 79, -1, -1));

        firstNameTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(firstNameTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 200, 30));

        jLabel11.setText("Addr Ln 2");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        addrLn2WrkTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrLn2WrkTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(addrLn2WrkTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 200, 30));

        jLabel12.setText("City");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        cityWrkTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityWrkTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(cityWrkTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 200, 30));

        jLabel13.setText("State");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        stateWrkTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateWrkTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(stateWrkTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 200, 30));

        jLabel14.setText("Zipcode");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        zipWrkTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipWrkTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(zipWrkTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 200, 30));

        jLabel15.setText("Addr Ln 1");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, 10));

        addrLn1HmTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrLn1HmTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(addrLn1HmTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 200, 30));

        jLabel16.setText("Addr Ln 2");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, 10));

        addrLn2HmTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrLn2HmTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(addrLn2HmTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 200, 30));

        jLabel17.setText("City");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 50, 20));

        cityHmTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityHmTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(cityHmTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 200, 30));

        jLabel18.setText("State");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 40, 20));

        stateHmTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateHmTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(stateHmTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 200, 30));

        jLabel19.setText("Zipcode");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, 10));

        zipHmTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipHmTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(zipHmTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 200, 30));

        jLabel20.setText("Zipcode");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 50, -1));

        zipLclTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipLclTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(zipLclTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, 200, 30));

        stateLclTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateLclTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(stateLclTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, 200, 30));

        cityLclTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityLclTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(cityLclTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 200, 30));

        addrLn2LclTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrLn2LclTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(addrLn2LclTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 200, 30));

        addrLn1LclTxtFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrLn1LclTxtFLdActionPerformed(evt);
            }
        });
        jPanel1.add(addrLn1LclTxtFLd, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 200, 30));

        jLabel21.setText("Addr Ln 1");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, -1, 10));

        jLabel22.setText("Addr Ln 2");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, 10));

        jLabel23.setText("City");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 50, 20));

        jLabel24.setText("State");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 40, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1065, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addrLn1WrkTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrLn1WrkTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrLn1WrkTxtFLdActionPerformed

    private void firstNameTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTxtFLdActionPerformed

    private void addrLn2WrkTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrLn2WrkTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrLn2WrkTxtFLdActionPerformed

    private void cityWrkTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityWrkTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityWrkTxtFLdActionPerformed

    private void stateWrkTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateWrkTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateWrkTxtFLdActionPerformed

    private void zipWrkTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipWrkTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipWrkTxtFLdActionPerformed

    private void addrLn1HmTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrLn1HmTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrLn1HmTxtFLdActionPerformed

    private void addrLn2HmTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrLn2HmTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrLn2HmTxtFLdActionPerformed

    private void cityHmTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityHmTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityHmTxtFLdActionPerformed

    private void stateHmTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateHmTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateHmTxtFLdActionPerformed

    private void zipHmTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipHmTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipHmTxtFLdActionPerformed

    private void zipLclTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipLclTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipLclTxtFLdActionPerformed

    private void stateLclTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateLclTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateLclTxtFLdActionPerformed

    private void cityLclTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityLclTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityLclTxtFLdActionPerformed

    private void addrLn2LclTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrLn2LclTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrLn2LclTxtFLdActionPerformed

    private void addrLn1LclTxtFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrLn1LclTxtFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrLn1LclTxtFLdActionPerformed

    private void lastNameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTxtFldActionPerformed

    private void dobTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTxtFldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrLn1HmTxtFLd;
    private javax.swing.JTextField addrLn1LclTxtFLd;
    private javax.swing.JTextField addrLn1WrkTxtFLd;
    private javax.swing.JTextField addrLn2HmTxtFLd;
    private javax.swing.JTextField addrLn2LclTxtFLd;
    private javax.swing.JTextField addrLn2WrkTxtFLd;
    private javax.swing.JTextField cityHmTxtFLd;
    private javax.swing.JTextField cityLclTxtFLd;
    private javax.swing.JTextField cityWrkTxtFLd;
    private javax.swing.JTextField dobTxtFld;
    private javax.swing.JTextField firstNameTxtFLd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameTxtFld;
    private javax.swing.JTextField ssnTxtFld;
    private javax.swing.JTextField stateHmTxtFLd;
    private javax.swing.JTextField stateLclTxtFLd;
    private javax.swing.JTextField stateWrkTxtFLd;
    private javax.swing.JTextField zipHmTxtFLd;
    private javax.swing.JTextField zipLclTxtFLd;
    private javax.swing.JTextField zipWrkTxtFLd;
    // End of variables declaration//GEN-END:variables
}
