/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageAirlines;

import Business.Airline.AirlineDirectory;
import javax.swing.JPanel;

/**
 *
 * @author vivekdalal
 */
public class ManageAirlinesJPanel extends javax.swing.JPanel {

    private AirlineDirectory airlineDirectory;
    private JPanel cardSequenceJPanel;

    /**
     * Creates new form ManageAirlinesJPanel
     */
    public ManageAirlinesJPanel(JPanel cardSequenceJPanel, AirlineDirectory airlineDirectory) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.airlineDirectory = airlineDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addAirlineBtn = new javax.swing.JButton();
        viewAirlineBtn = new javax.swing.JButton();
        searchAirlineBtn = new javax.swing.JButton();
        searchTxtFld = new javax.swing.JTextField();
        updateAirlineBtn = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        jLabel1.setText("Manage Airlines");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, 140, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 600, 160));

        addAirlineBtn.setText("Add Airline");
        addAirlineBtn.setMaximumSize(new java.awt.Dimension(120, 30));
        addAirlineBtn.setMinimumSize(new java.awt.Dimension(120, 30));
        addAirlineBtn.setPreferredSize(new java.awt.Dimension(120, 30));
        addAirlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAirlineBtnActionPerformed(evt);
            }
        });
        add(addAirlineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 130, -1));

        viewAirlineBtn.setText("View Airline");
        viewAirlineBtn.setMaximumSize(new java.awt.Dimension(120, 30));
        viewAirlineBtn.setMinimumSize(new java.awt.Dimension(120, 30));
        viewAirlineBtn.setPreferredSize(new java.awt.Dimension(120, 30));
        add(viewAirlineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 130, -1));

        searchAirlineBtn.setText("Search Airline");
        searchAirlineBtn.setMaximumSize(new java.awt.Dimension(120, 30));
        searchAirlineBtn.setMinimumSize(new java.awt.Dimension(120, 30));
        searchAirlineBtn.setPreferredSize(new java.awt.Dimension(120, 30));
        add(searchAirlineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 130, -1));

        searchTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtFldActionPerformed(evt);
            }
        });
        add(searchTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 190, -1));

        updateAirlineBtn.setText("Update Airline");
        updateAirlineBtn.setMaximumSize(new java.awt.Dimension(120, 30));
        updateAirlineBtn.setMinimumSize(new java.awt.Dimension(120, 30));
        updateAirlineBtn.setPreferredSize(new java.awt.Dimension(120, 30));
        add(updateAirlineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void searchTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtFldActionPerformed

    private void addAirlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAirlineBtnActionPerformed
        // Manage Airline button action code goes here.
//        AddNewAirlineJPanel addNewAirlineJPanel = new AddNewAirlineJPanel(cardSequenceJPanel, airline);
//        cardSequenceJPanel.add("AddNewAirlineJPanel", addNewAirlineJPanel);
//        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
//        cardLayout.next(cardSequenceJPanel);

    }//GEN-LAST:event_addAirlineBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAirlineBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchAirlineBtn;
    private javax.swing.JTextField searchTxtFld;
    private javax.swing.JButton updateAirlineBtn;
    private javax.swing.JButton viewAirlineBtn;
    // End of variables declaration//GEN-END:variables
}
