/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Business.VitalSigns;
import Utility.Validator;
import javax.swing.JOptionPane;

/**
 *
 * @author vivekdalal
 */
public class CreateVSPanel extends javax.swing.JPanel {

    private VitalSignHistory vitalSignHistory;

    /**
     * Creates new form CreatePanel
     */
    CreateVSPanel(VitalSignHistory vitalSignHistory) {
        initComponents();
        this.vitalSignHistory = vitalSignHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateTxtFld = new javax.swing.JTextField();
        tempTxtFld = new javax.swing.JTextField();
        bloodPressureTxtFld = new javax.swing.JTextField();
        pulseTxtFld = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setText("Create Vital Sign");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, -1));

        jLabel2.setText("Date");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel3.setText("Temperature");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setText("Blood Pressure");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setText("Pulse");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        add(dateTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 200, -1));
        add(tempTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 200, -1));
        add(bloodPressureTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 200, -1));
        add(pulseTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 200, -1));

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        //Save button click action code goes here
        try {
            if (!Validator.isValidDouble(tempTxtFld.getText())) {
                JOptionPane.showMessageDialog(null, "Temperature value can only be a number. Decimals are allowed. Please check");
                throw new Exception();
            }

            if (!Validator.isValidDouble(bloodPressureTxtFld.getText())) {
                JOptionPane.showMessageDialog(null, "Blood Pressure value can only be a number. Decimals are allowed. Please check");
                throw new Exception();
            }

            if (!Validator.isValidNum(pulseTxtFld.getText())) {
                JOptionPane.showMessageDialog(null, "Pulse value can only be a number. Please check");
                throw new Exception();
            }

            if (!Validator.isValidData(dateTxtFld.getText())) {
                JOptionPane.showMessageDialog(null, "Date value is not valid. Please check");
                throw new Exception();
            }

            double temperature = Double.parseDouble(tempTxtFld.getText());
            double bloodPressure = Double.parseDouble(bloodPressureTxtFld.getText());
            int pulse = Integer.parseInt(pulseTxtFld.getText());
            String date = dateTxtFld.getText();

            VitalSigns vitalSigns = vitalSignHistory.addVitalSign();
            vitalSigns.setTemperature(temperature);
            vitalSigns.setBloodPressure(bloodPressure);
            vitalSigns.setPulse(pulse);
            vitalSigns.setDate(date);

            JOptionPane.showMessageDialog(null, "Vital Signs added successfully.");
            tempTxtFld.setText("");
            bloodPressureTxtFld.setText("");
            pulseTxtFld.setText("");
            dateTxtFld.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Vital Sign not created. Please enter valid data");

        }

    }//GEN-LAST:event_saveBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodPressureTxtFld;
    private javax.swing.JTextField dateTxtFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pulseTxtFld;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField tempTxtFld;
    // End of variables declaration//GEN-END:variables
}
