/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Utility.Validator;
import javax.swing.JOptionPane;

/**
 *
 * @author vivekdalal
 */
public class VitalSignMainJFrame extends javax.swing.JFrame {

    private VitalSignHistory vitalSignHistory;

    /**
     * Creates new form VitalSignMainJFrame
     */
    public VitalSignMainJFrame() {
        initComponents();
        vitalSignHistory = new VitalSignHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masterPanel = new javax.swing.JPanel();
        mainSplitPane = new javax.swing.JSplitPane();
        leftSplitPane = new javax.swing.JPanel();
        createVSBtn = new javax.swing.JButton();
        viewVSBtn = new javax.swing.JButton();
        minBPTxtFld = new javax.swing.JTextField();
        maxBPTxtFld = new javax.swing.JTextField();
        abnormalVSBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rightSplitPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftSplitPane.setBackground(new java.awt.Color(204, 255, 255));

        createVSBtn.setText("Create Vital Sign");
        createVSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVSBtnActionPerformed(evt);
            }
        });

        viewVSBtn.setText("View Vital Signs");
        viewVSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVSBtnActionPerformed(evt);
            }
        });

        abnormalVSBtn.setText("Abnormal");
        abnormalVSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abnormalVSBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Min BP");

        jLabel2.setText("Max BP");

        javax.swing.GroupLayout leftSplitPaneLayout = new javax.swing.GroupLayout(leftSplitPane);
        leftSplitPane.setLayout(leftSplitPaneLayout);
        leftSplitPaneLayout.setHorizontalGroup(
            leftSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSplitPaneLayout.createSequentialGroup()
                .addGroup(leftSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftSplitPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(leftSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createVSBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewVSBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(abnormalVSBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(leftSplitPaneLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(leftSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxBPTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minBPTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftSplitPaneLayout.setVerticalGroup(
            leftSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSplitPaneLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(createVSBtn)
                .addGap(18, 18, 18)
                .addComponent(viewVSBtn)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minBPTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(maxBPTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(abnormalVSBtn)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        mainSplitPane.setLeftComponent(leftSplitPane);

        rightSplitPane.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout rightSplitPaneLayout = new javax.swing.GroupLayout(rightSplitPane);
        rightSplitPane.setLayout(rightSplitPaneLayout);
        rightSplitPaneLayout.setHorizontalGroup(
            rightSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        rightSplitPaneLayout.setVerticalGroup(
            rightSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );

        mainSplitPane.setRightComponent(rightSplitPane);

        javax.swing.GroupLayout masterPanelLayout = new javax.swing.GroupLayout(masterPanel);
        masterPanel.setLayout(masterPanelLayout);
        masterPanelLayout.setHorizontalGroup(
            masterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterPanelLayout.createSequentialGroup()
                .addComponent(mainSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        masterPanelLayout.setVerticalGroup(
            masterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(masterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createVSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVSBtnActionPerformed
        //Create Vital Sign button action code goes here
        CreateVSPanel createVSPanel = new CreateVSPanel(vitalSignHistory);
        mainSplitPane.setRightComponent(createVSPanel);
    }//GEN-LAST:event_createVSBtnActionPerformed

    private void viewVSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVSBtnActionPerformed
        // View Vital Sign button click action goes here
        ViewVSPanel viewVSPanel = new ViewVSPanel(vitalSignHistory);
        mainSplitPane.setRightComponent(viewVSPanel);
    }//GEN-LAST:event_viewVSBtnActionPerformed

    private void abnormalVSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abnormalVSBtnActionPerformed
        // Abnormal Vital Sign button click action goes here

        try {
            String maxBPStr = maxBPTxtFld.getText();
            String minBPStr = minBPTxtFld.getText();

            if (!Validator.isValidDouble(minBPStr)) {
                JOptionPane.showMessageDialog(null, "Minimum BP value can only be a number. Decimals are allowed. Please check");
                throw new Exception();
            }

            if (!Validator.isValidDouble(maxBPStr)) {
                JOptionPane.showMessageDialog(null, "Maximum BP value can only be a number. Decimals are allowed. Please check");
                throw new Exception();
            }

            double maxBP = maxBPStr.equals("") ? Double.MAX_VALUE : Double.parseDouble(maxBPStr);
            double minBP = minBPStr.equals("") ? Double.MIN_VALUE : Double.parseDouble(minBPStr);

            if (maxBP <= minBP) {
                //Illogical Inputs passed. Showing Error message and skipping the next steps
                JOptionPane.showMessageDialog(null, "Max BP cannot be less than or equal to Min BP.");
                throw new Exception();
            }

            AbnormalVSPanel abnormalVSPanel = new AbnormalVSPanel(vitalSignHistory, maxBP, minBP);
            mainSplitPane.setRightComponent(abnormalVSPanel);
        } catch (Exception e) {
            //Do nothing for now. Once a logger is integrated in the application we can
        }

    }//GEN-LAST:event_abnormalVSBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VitalSignMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VitalSignMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VitalSignMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VitalSignMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VitalSignMainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abnormalVSBtn;
    private javax.swing.JButton createVSBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel leftSplitPane;
    private javax.swing.JSplitPane mainSplitPane;
    private javax.swing.JPanel masterPanel;
    private javax.swing.JTextField maxBPTxtFld;
    private javax.swing.JTextField minBPTxtFld;
    private javax.swing.JPanel rightSplitPane;
    private javax.swing.JButton viewVSBtn;
    // End of variables declaration//GEN-END:variables
}
