/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airline.AirlineDirectory;
import Interface.ManageAirlines.ManageAirlinesJPanel;
import java.awt.CardLayout;

/**
 *
 * @author vivekdalal
 */
public class TravelAgencyMain extends javax.swing.JFrame {

    private AirlineDirectory airlineDirectory;

    /**
     * Creates new form TravelAgencyMain
     */
    public TravelAgencyMain() {
        initComponents();
        airlineDirectory = new AirlineDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        cardSequenceJPanel = new javax.swing.JPanel();
        ActionsJPanel = new javax.swing.JPanel();
        manageAirlineBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jSplitPane1.setDividerLocation(800);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jSplitPane1.setSize(new java.awt.Dimension(1000, 600));

        cardSequenceJPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        cardSequenceJPanel.setSize(new java.awt.Dimension(800, 600));
        cardSequenceJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setLeftComponent(cardSequenceJPanel);

        ActionsJPanel.setPreferredSize(new java.awt.Dimension(200, 600));
        ActionsJPanel.setSize(new java.awt.Dimension(200, 600));
        ActionsJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageAirlineBtn.setText("Manage Airlines");
        manageAirlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAirlineBtnActionPerformed(evt);
            }
        });
        ActionsJPanel.add(manageAirlineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 130, -1));

        jSplitPane1.setRightComponent(ActionsJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageAirlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAirlineBtnActionPerformed
        // Manage Airline button action code goes here.
        ManageAirlinesJPanel manageAirlinesJPanel = new ManageAirlinesJPanel(cardSequenceJPanel, airlineDirectory);
        cardSequenceJPanel.add("ManageAirlinesJPanel", manageAirlinesJPanel);
        CardLayout cardLayout = (CardLayout) cardSequenceJPanel.getLayout();
        cardLayout.next(cardSequenceJPanel);

    }//GEN-LAST:event_manageAirlineBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActionsJPanel;
    private javax.swing.JPanel cardSequenceJPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageAirlineBtn;
    // End of variables declaration//GEN-END:variables
}
