/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfacePackage.Panels.View;

import BusinessPackage.DemographicInfo;

/**
 *
 * @author vivekdalal
 */
public class ViewPIPanel extends javax.swing.JPanel {

    private DemographicInfo personalInfo;

    /**
     * Creates new form ViewPIPanel
     */
    //public ViewPIPanel() {
    //    initComponents();
    //}
    public ViewPIPanel(DemographicInfo personalInfo) {
        initComponents();
        this.personalInfo = personalInfo;
        updateView();
    }

    private void updateView() {
//        fnTxtFLd.setText(Assignment1MainJFrameSplitted.personalInfo.getFirstName());
//        fnTxtFLd.setEditable(false);
//        lnTxtFLd.setText(Assignment1MainJFrameSplitted.personalInfo.getLastName());
//        lnTxtFLd.setEditable(false);
//        pnTxtFLd.setText(Integer.toString(Assignment1MainJFrameSplitted.personalInfo.getPhoneNum()));
//        pnTxtFLd.setEditable(false);
//        dobTxtFLd.setText(Assignment1MainJFrameSplitted.personalInfo.getDateOfBirth());
//        dobTxtFLd.setEditable(false);
//        ageTxtFLd.setText(Integer.toString(Assignment1MainJFrameSplitted.personalInfo.getAge()));
//        ageTxtFLd.setEditable(false);
//        hghtTxtFLd.setText(Double.toString(Assignment1MainJFrameSplitted.personalInfo.getHeight()));
//        hghtTxtFLd.setEditable(false);
//        wghtTxtFLd.setText(Double.toString(Assignment1MainJFrameSplitted.personalInfo.getWeight()));
//        wghtTxtFLd.setEditable(false);
//        ssnTxtFLd.setText(Integer.toString(Assignment1MainJFrameSplitted.personalInfo.getSSN()));
//        ssnTxtFLd.setEditable(false);

        fnTxtFLd.setText(personalInfo.getFirstName());
        fnTxtFLd.setEditable(false);
        lnTxtFLd.setText(personalInfo.getLastName());
        lnTxtFLd.setEditable(false);
        pnTxtFLd.setText(personalInfo.getPhoneNum());
        pnTxtFLd.setEditable(false);
        dobTxtFLd.setText(personalInfo.getDateOfBirth());
        dobTxtFLd.setEditable(false);
        ageTxtFLd.setText(Integer.toString(personalInfo.getAge()));
        ageTxtFLd.setEditable(false);
        hghtTxtFLd.setText(Double.toString(personalInfo.getHeight()));
        hghtTxtFLd.setEditable(false);
        wghtTxtFLd.setText(Double.toString(personalInfo.getWeight()));
        wghtTxtFLd.setEditable(false);
        ssnTxtFLd.setText(Integer.toString(personalInfo.getSSN()));
        ssnTxtFLd.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fnTxtFLd = new javax.swing.JTextField();
        lnTxtFLd = new javax.swing.JTextField();
        pnTxtFLd = new javax.swing.JTextField();
        dobTxtFLd = new javax.swing.JTextField();
        ageTxtFLd = new javax.swing.JTextField();
        ssnTxtFLd = new javax.swing.JTextField();
        wghtTxtFLd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hghtTxtFLd = new javax.swing.JTextField();

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Phone Number");

        jLabel4.setText("Date of Birth");

        jLabel5.setText("SSN");

        jLabel6.setText("Age");

        jLabel7.setText("Height");

        jLabel8.setText("Weight");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fnTxtFLd, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lnTxtFLd)
                    .addComponent(pnTxtFLd)
                    .addComponent(dobTxtFLd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ssnTxtFLd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wghtTxtFLd, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(ageTxtFLd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hghtTxtFLd))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnTxtFLd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(ageTxtFLd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(hghtTxtFLd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lnTxtFLd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pnTxtFLd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wghtTxtFLd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobTxtFLd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssnTxtFLd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(170, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTxtFLd;
    private javax.swing.JTextField dobTxtFLd;
    private javax.swing.JTextField fnTxtFLd;
    private javax.swing.JTextField hghtTxtFLd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lnTxtFLd;
    private javax.swing.JTextField pnTxtFLd;
    private javax.swing.JTextField ssnTxtFLd;
    private javax.swing.JTextField wghtTxtFLd;
    // End of variables declaration//GEN-END:variables
}
