/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfacePackage.Panels.View;

import BusinessPackage.DriverLicenseInfo;

/**
 *
 * @author vivekdalal
 */
public class ViewDLPanel extends javax.swing.JPanel {

    private DriverLicenseInfo driverLicenseInfo;

    /**
     * Creates new form ViewDLPanel
     */
    public ViewDLPanel() {
        initComponents();

        updateView();
    }

    public ViewDLPanel(DriverLicenseInfo driverLicenseInfo) {
        initComponents();
        this.driverLicenseInfo = driverLicenseInfo;
        updateView();
    }

    private void updateView() {

        dlNumFld.setText(driverLicenseInfo.getLicenseNum());
        dlNumFld.setEditable(false);
        dtIssuedFld.setText(driverLicenseInfo.getDateIssued());
        dlNumFld.setEditable(false);
        dtExpiryFld.setText(driverLicenseInfo.getDateExpiry());
        dtExpiryFld.setEditable(false);
        bloodTypFld.setText(driverLicenseInfo.getBloodTyp());
        bloodTypFld.setEditable(false);
    }

//    public ViewDLPanel(DriverLicenseInfo driverLicenseInfo) {
//        initComponents();
//        this.driverLicenseInfo = driverLicenseInfo;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlNumFld = new javax.swing.JTextField();
        dtIssuedFld = new javax.swing.JTextField();
        dtExpiryFld = new javax.swing.JTextField();
        bloodTypFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        dlNumFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlNumFldActionPerformed(evt);
            }
        });

        dtIssuedFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtIssuedFldActionPerformed(evt);
            }
        });

        dtExpiryFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtExpiryFldActionPerformed(evt);
            }
        });

        bloodTypFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodTypFldActionPerformed(evt);
            }
        });

        jLabel1.setText("Driving License Number");

        jLabel2.setText("Date of Issue");

        jLabel3.setText("Date of Expiry");

        jLabel4.setText("Blood Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bloodTypFld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtExpiryFld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtIssuedFld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlNumFld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dlNumFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtIssuedFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtExpiryFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bloodTypFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dlNumFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlNumFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlNumFldActionPerformed

    private void dtIssuedFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtIssuedFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtIssuedFldActionPerformed

    private void dtExpiryFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtExpiryFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtExpiryFldActionPerformed

    private void bloodTypFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodTypFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTypFldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodTypFld;
    private javax.swing.JTextField dlNumFld;
    private javax.swing.JTextField dtExpiryFld;
    private javax.swing.JTextField dtIssuedFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
