/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author vivekdalal
 */
public class UpdatePanel extends javax.swing.JPanel {

    private Product product;

    /**
     * Creates new form updatePanel
     */
    public UpdatePanel() {
        initComponents();
    }

    //Creating a parameterized constructor
    public UpdatePanel(Product product) {
        initComponents();

        //Assigning the product which has been created on the MainJFrame to the product object in the UpdatePanel
        this.product = product;
        //Populating values to be displayed on the update screen
        populateComponent();
    }

    //Pre-Populating the data set via the create Panel
    private void populateComponent() {
        nameTxtFld.setText(product.getName());
        priceTxtFld.setText(product.getPrice());
        availibilityNoTxtFld.setText(product.getAvailNum());
        descriptionTxtFld.setText(product.getDescription());

        //Populating the supplier information
        supplierNameTxtFld.setText(product.getSupplier().getName());
        supplierAddrTxtFld.setText(product.getSupplier().getAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameTxtFld = new javax.swing.JTextField();
        priceTxtFld = new javax.swing.JTextField();
        availibilityNoTxtFld = new javax.swing.JTextField();
        descriptionTxtFld = new javax.swing.JTextField();
        editBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        supplierAddrTxtFld = new javax.swing.JTextField();
        supplierNameTxtFld = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setText("Price");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel3.setText("Availibility No");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel4.setText("Description");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        add(nameTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, -1));
        add(priceTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 200, -1));
        add(availibilityNoTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 200, -1));
        add(descriptionTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 200, -1));

        editBtn.setText("Edit/Update");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 445, -1, -1));

        jLabel6.setText("Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 330, -1, -1));

        jLabel7.setText("Address");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 373, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel8.setText("Product Infomation");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 201, 32));

        jLabel5.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel5.setText("Update Your Product");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 0, -1, -1));
        add(supplierAddrTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 200, -1));

        supplierNameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierNameTxtFldActionPerformed(evt);
            }
        });
        add(supplierNameTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 200, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel9.setText("Supplier Infomation");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 201, 32));
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        //Edit/Update Button has been clicked.
        product.setName(nameTxtFld.getText());
        product.setPrice(priceTxtFld.getText());
        product.setAvailNum(availibilityNoTxtFld.getText());
        product.setDescription(descriptionTxtFld.getText());

        //Updating the supplier fields
        product.getSupplier().setName(supplierNameTxtFld.getText());
        product.getSupplier().setAddress(supplierAddrTxtFld.getText());

        // prompt user that product was successfully ceated
        JOptionPane.showMessageDialog(null, "product successfully edited/updated.");
    }//GEN-LAST:event_editBtnActionPerformed

    private void supplierNameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierNameTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierNameTxtFldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availibilityNoTxtFld;
    private javax.swing.JTextField descriptionTxtFld;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTxtFld;
    private javax.swing.JTextField priceTxtFld;
    private javax.swing.JTextField supplierAddrTxtFld;
    private javax.swing.JTextField supplierNameTxtFld;
    // End of variables declaration//GEN-END:variables
}
