/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;

/**
 *
 * @author vivekdalal
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    private Product product;

    public ViewPanel(Product product) {
        initComponents();
        //Assigning the product which has been created on the MainJFrame to the product object in the ViewPanel
        this.product = product;

        //Displaying values on the View Panel
        displayProduct(product);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        availNumTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        supplierNameTxtFld = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        supplierAddrTxtFld = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("View Your Product");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 6, -1, -1));

        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 63, -1, -1));

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 58, 241, -1));

        jLabel3.setText("Price:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });
        add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 96, 241, -1));

        jLabel4.setText("Availabity Number:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, 129, -1));

        availNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availNumTextFieldActionPerformed(evt);
            }
        });
        add(availNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 134, 241, -1));

        jLabel5.setText("Description:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 177, -1, -1));

        descriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTextFieldActionPerformed(evt);
            }
        });
        add(descriptionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 172, 241, -1));

        jLabel6.setText("Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 300, -1, -1));

        jLabel7.setText("Address");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 343, -1, -1));

        supplierNameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierNameTxtFldActionPerformed(evt);
            }
        });
        add(supplierNameTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 295, 230, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel8.setText("Supplier Infomation");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 227, 201, 32));

        supplierAddrTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierAddrTxtFldActionPerformed(evt);
            }
        });
        add(supplierAddrTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 338, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void availNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availNumTextFieldActionPerformed

    private void descriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionTextFieldActionPerformed

    private void supplierNameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierNameTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierNameTxtFldActionPerformed

    private void supplierAddrTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierAddrTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierAddrTxtFldActionPerformed

    private void displayProduct(Product product) {

        String productName = product.getName();
        nameTextField.setText(productName);
        //setEnabled(false) will make the fields uneditable
        nameTextField.setEnabled(false);

        String productPrice = product.getPrice();
        priceTextField.setText(productPrice);
        priceTextField.setEnabled(false);

        String productAvailNum = product.getAvailNum();
        availNumTextField.setText(productAvailNum);
        availNumTextField.setEnabled(false);

        String productDescription = product.getDescription();
        descriptionTextField.setText(productDescription);
        descriptionTextField.setEnabled(false);

        //Setting the supplier information on the View screen
        String supplierName = product.getSupplier().getName();
        supplierNameTxtFld.setText(supplierName);
        supplierNameTxtFld.setEnabled(false);

        String supplierAddr = product.getSupplier().getAddress();
        supplierAddrTxtFld.setText(supplierAddr);
        supplierAddrTxtFld.setEnabled(false);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availNumTextField;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField supplierAddrTxtFld;
    private javax.swing.JTextField supplierNameTxtFld;
    // End of variables declaration//GEN-END:variables
}
